name: songguanxingyi
on:
  workflow_dispatch:

  schedule:
    - cron: '51 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: songguanxingyi
        env:
          hjalo77: ${{ secrets.hjalo77 }}
        run: |
          printf '%s' "$hjalo77" | jq -r .mive148 | /bin/bash
          printf '%s' "$ts89969" | jq -r .mbu958 | /bin/bash
          printf '%s' "$k83071" | jq -r .qhv293 | /bin/bash
          echo $mygfx27 | jq -r .pfs08 | /bin/bash
          printf '%s' "$gkzjs3147" | jq -r .x157 | /bin/bash
          printf '%s' "$g2" | jq -r .wagcn8516 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 67ttHKiS
          path: "*.zip"
          retention-days: 1
